site_name: OpenSAFELY Data Builder documentation
repo_url: https://github.com/opensafely-core/databuilder
docs_dir: docs

nav:
  - Home: toc.md
  - Quick Start: quick-start.md


theme:
  name: material


watch:
  - docs


plugins:
  - table-reader:
      base_path: "docs_dir"


markdown_extensions:
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "🔗"
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - admonition
  - footnotes
  - abbr
  - md_in_html
