site_name: OpenSAFELY Data Builder documentation
repo_url: https://github.com/opensafely-core/databuilder
docs_dir: docs

nav:
  - Home: toc.md
  - Quick Start: quick-start.md


theme:
  name: material


watch:
  - docs


plugins:
  - mkdocs-opensafely-databuilder
