# NOTE: This mkdocs.yml contains the minimum config required to run
# ehrQL's docs locally.  These docs do not run in isolation in production.
#
# In production, the ehrql docs are pulled into and built with the main docs at
# https://github.com/opensafely/documentation
#
# The contents of this mkdocs.yml are ignore in the production build.
#
site_name: OpenSAFELY ehrQL documentation
repo_url: https://github.com/opensafely-core/ehrql
docs_dir: docs

nav:
  - ehrQL: index.md
  - Tutorial:
    - Tutorial: tutorial/index.md
    - Installation and setup of ehrQL: tutorial/installation-and-setup.md
    - Running ehrQL: tutorial/running-ehrql.md
    - ehrQL concepts in depth: tutorial/dataset-definition-concepts.md
  - How-to guides:
    - How-to guides: how-to/index.md
    - Using ehrQL to answer specific questions: how-to/examples.md
    - Resolving ehrQL errors: how-to/errors.md
  - Reference:
    - Reference: reference/index.md
    - ehrQL language reference: reference/language.md
    - ehrQL language features: reference/features.md
    - ehrQL backends: reference/backends.md
    - ehrQL table schemas: reference/schemas.md
    - ehrQL command line interface: reference/cli.md
  - Explanation:
    - Explanation: explanation/index.md
    - ehrQL backend tables: explanation/backend-tables.md
    - ehrQL output formats: explanation/output-formats.md
    - Using ehrQL in OpenSAFELY projects: explanation/using-ehrql-in-opensafely-projects.md
    - Guidance for existing cohort-extractor users: explanation/guidance-for-existing-cohort-extractor-users.md

theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.indexes

extra_css:
  - stylesheets/extra.css

watch:
  - docs

plugins:
  - table-reader:
      base_path: "docs_dir"


# WARNING!
# This markdown_extensions config (with the exception of the snippets base_path) is duplicated
# from the mkdocs.yml in the parent repo (https://github.com/opensafely/documentation) in order
# to build local docs with similar styling. If any changes/additions are needed, ensure they are
# made in the parent repo also.
markdown_extensions:
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "🔗"
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - admonition
  - footnotes
  - abbr
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# This hook adds some clarifying studying around snippets that will be incorporated
# from the parent repo, and is relevant for local development only.
hooks:
  - hooks/parent_snippets.py
