version: "3.0"

expectations:
  population_size: 1000

actions:
  extract_data:
    run: ehrql:v0 generate-dataset "./analysis/dataset_definition.py" --output "output/data_extract.arrow" --dummy-tables "example-data/"
    outputs:
      highly_sensitive:
        population: output/data_extract.arrow
