version: "3.0"

expectations:
  population_size: 1000

actions:
  extract_data:
    run: ehrql:v0 generate-dataset "./dataset_definition.py" --output "outputs/data_extract.csv" --dummy-tables "example-data/"
    outputs:
      highly_sensitive:
        population: outputs/data_extract.csv
