site_name: OpenSAFELY Data Builder documentation
repo_url: https://github.com/opensafely-core/databuilder
docs_dir: mkdocs

nav:
  - Home: toc.md
  - Quick Start: quick-start.md


theme:
  name: material


watch:
  - mkdocs


plugins:
  - mkdocs-opensafely-databuilder
  - table-reader

markdown_extensions:
  - pymdownx.snippets:
      base_path: docs
