name: Build and publish image

on:
  create:
  workflow_dispatch:
  # Nb: workflow_run only triggers on the default branch
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run
  workflow_run:
    workflows:
      - CI
    status:
      - completed

jobs:
  # TODO: refactor into two small tag jobs & one build job
  # - we can't use needs:, can we use env vars?
  # - actually the from main job should now work for both cases?
  build-and-publish-docker-image-from-create-tag:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    env:
      image: ghcr.io/opensafely-core/cohortextractor-v2
    steps:
      - uses: actions/checkout@v2

      - name: Get current git tag
        id: tags
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.image }}:latest

      - name: Log into GitHub Container Registry
        run: docker login https://ghcr.io -u ${{ github.actor }} --password ${{ secrets.DOCKER_RW_TOKEN }}

      - name: Push image to GitHub Container Registry
        env:
          VERSION: ${{ steps.tags.outputs.tag }}
        run: |
          docker tag ${{ env.image }} ${{ env.image }}:$VERSION
          docker push ${{ env.image }}:$VERSION

  build-and-publish-docker-image-from-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      image: ghcr.io/opensafely-core/cohortextractor-v2
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustagref
        uses: "WyriHaximus/github-action-get-previous-tag@8a0e045f02c0a3a04e1452df58b90fc7e555e950"

      - name: Debug
        run: echo ${{ steps.previoustagref.outputs.tag }}

      - name: 
        id: previoustagcommit
        # if we are on a tag, should look like `v0.6.0`
        # if we are not on a tag, should look like `v0.6.0-24-gbf6352d`
        run: echo ::set-output name=tag_describe::`git describe --tags`

      - name: Debug
        run: echo ${{ steps.previoustagref.outputs.tag }} -- ${{ steps.previoustagcommit.outputs.tag_describe }}

      - name: Fail if not tagged commit
        if: ${{ steps.previoustagcommit.outputs.tag_describe != steps.previoustagref.outputs.tag }}
        run: /bin/false

      # TODO: check if this tag has been published on docker

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.image }}:latest

      - name: Log into GitHub Container Registry
        run: docker login https://ghcr.io -u ${{ github.actor }} --password ${{ secrets.DOCKER_RW_TOKEN }}

      - name: Push image to GitHub Container Registry
        env:
          VERSION: ${{ steps.previoustagref.outputs.tag }}
        run: |
          docker tag ${{ env.image }} ${{ env.image }}:$VERSION
          docker push ${{ env.image }}:$VERSION
