---
name: 'Check docs links'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: '14 4 * * *'

permissions:
  contents: read

jobs:
  check_docs_links:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout docs repo
        uses: actions/checkout@v3
        with:
          repository: opensafely/documentation
          submodules: true

      - name: Install Python and just
        uses: opensafely-core/setup-action@v1
        with:
          install-just: true
          python-version: '3.9'

      - name: Build docs site
        env:
          AccessToken: ${{ secrets.GITHUB_TOKEN }}
          MKDOCS_SITE_URL: https://docs.opensafely.org
          MKDOCS_MULTIREPO_CLEANUP: true
          DATABUILDER_BRANCH: main
        run: just build

      - name: Check links in built databuilder docs
        uses: lycheeverse/lychee-action@9ace499fe66cee282a29eaa628fdac2c72fa087f  # v1.6.1
        with:
          args: "--exclude-all-private --exclude-mail --include-verbatim --require-https --verbose --no-progress
          './**/data-builder/*.md' './**/data-builder/*.html'"
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: "Notify Slack on Failure"
        if: failure()
        uses: voxmedia/github-action-slack-notify-build@3665186a8c1a022b28a1dbe0954e73aa9081ea9e # v1.6.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel_id: C03FB777L1M
          status: "Databuilder Check Docs Links Failure"
          color: danger
