---
name: Databricks CI

on:
  workflow_dispatch:
    inputs:
      test_args:
        description: "Tests to run or other pytest args"
        required: true
        default: "tests/spec -k 'spark'"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: opensafely-core/setup-action@v1
        with:
          install-just: true
          python-version: "3.9"
      - name: Login to databricks
        run: |
            echo -e \
            "[DEFAULT]
            host = https://drtl-theta.cloud.databricks.com
            username = simon.davy@thedatalab.org
            password = ${{ secrets.DATABRICKS_PASSWORD }}
            jobs-api-version = 2.0" \
            >> ~/.databrickscfg

      - name: Run Databricks tests
        run:
            just databricks-test ${{ github.event.inputs.test_args }}
