---
name: Long-running generative tests

on:
  workflow_dispatch:
  schedule:
    - cron:  "13 3 * * *"

jobs:
  gentests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: opensafely-core/setup-action@v1
        with:
          install-just: true
          python-version: "3.9"
      - run: GENTEST_EXAMPLES=40000 GENTEST_COMPREHENSIVE=t GENTEST_DEBUG=t just test-generative
