---
name: Long-running generative tests

on:
  workflow_dispatch:
  schedule:
    - cron:  "26 0 * * *"

jobs:
  gentests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: opensafely-core/setup-action@v1
        with:
          install-just: true
          python-version: "3.11"
      # To work around memory leak issues in our database containers we run the
      # tests in multiple smaller batches, recreating the containers between
      # each batch
      - name: Run `just test tests/generative/test_query_model.py::test_query_model` in batches
        run: |
          set -euo pipefail
          start_time=$(date +%s)

          just devenv
          export \
            GENTEST_EXAMPLES=200 \
            GENTEST_RANDOMIZE=t \
            GENTEST_MAX_DEPTH=30 \
            GENTEST_DEBUG=t \
            GENTEST_CHECK_IGNORED_ERRORS=t

          # We get a maximum of 6 hours runtime with Github Actions so breaking
          # the loop after 4 hours feels like a reasonably balance of getting a
          # decent amount of generative testing done while leaving plenty of
          # headroom.
          end_time=$((start_time + 4 * 3600))
          i=1

          while true; do
            echo
            echo "==> Running test batch $i with $GENTEST_EXAMPLES examples"
            echo

            # Do the actual testing
            just test tests/generative/test_query_model.py::test_query_model

            if [[ $(date +%s) -ge $end_time ]]; then
              break
            fi

            just remove-database-containers
            ((i++))
          done

      - name: "Notify Slack on Failure"
        if: failure() && github.ref_name == 'main'
        uses: voxmedia/github-action-slack-notify-build@3665186a8c1a022b28a1dbe0954e73aa9081ea9e # v1.6.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel_id: C03FB777L1M
          status: "Generative Test Failure"
          color: danger
