---
name: Long-running generative tests

on:
  workflow_dispatch:
  schedule:
    - cron:  "13 3 * * *"

jobs:
  gentests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: opensafely-core/setup-action@v1
        with:
          install-just: true
          python-version: "3.11"
      - run: |
          GENTEST_EXAMPLES=5000 \
          GENTEST_RANDOMIZE=t \
          GENTEST_MAX_DEPTH=30 \
          GENTEST_DEBUG=t \
          GENTEST_CHECK_IGNORED_ERRORS=t \
          just test-generative

      - name: "Notify Slack on Failure"
        if: failure() && github.ref_name == 'main'
        uses: voxmedia/github-action-slack-notify-build@3665186a8c1a022b28a1dbe0954e73aa9081ea9e # v1.6.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel_id: C03FB777L1M
          status: "Generative Test Failure"
          color: danger
