---
name: Long-running generative tests

on:
  workflow_dispatch:
  schedule:
    - cron:  "13 3 * * *"

jobs:
  gentests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.9"
      - name: Install just
        run: |
          mkdir -p ~/.local/bin
          curl -L https://github.com/casey/just/releases/download/1.9.0/just-1.9.0-x86_64-unknown-linux-musl.tar.gz \
           | tar -xzf - --directory ~/.local/bin just
      - run: GENTEST_EXAMPLES=40000 GENTEST_COMPREHENSIVE=t GENTEST_DEBUG=t just test-generative
