---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - uses: extractions/setup-just@v1
      - name: Check formatting, linting and import sorting
        run: just check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - uses: extractions/setup-just@v1
      - name: Run tests
        env:
          CI: 1
        run: just test-all

  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          failure-threshold: error

  tag-new-version:
    # This uses `conventional commits` to generate tags.  A full list
    # of valid prefixes is here:
    # https://github.com/commitizen/conventional-commit-types/blob/master/index.json
    #
    # fix, perf -> patch release
    # feat -> minor release
    # BREAKING CHANGE in footer -> major release
    #
    # anything else (docs, refactor, etc) does not create a release
    needs: [check, test]
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@981ffb2cc3f2b684b2bfd8ee17bc8d781368ba60
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          release_branches: main

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install package
      run: pip install .
