---
name: "Create PR to update `external_studies` test code"

on:
  workflow_dispatch:
  schedule:
    - cron:  "43 2 * * *"

jobs:
  create_external_studies_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: opensafely-core/setup-action@v1
        with:
          install-just: true
          python-version: "3.9"

      - name: Update vendored copies of external study code
        run: just update-external-studies

      - name: Create a Pull Request if there are any changes
        id: create_pr
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          add-paths: tests/acceptance/external_studies/*
          branch: bot/update-external-studies
          base: main
          commit-message: "chore: Update `external_studies` test code"
          title: "Update `external_studies` test code"
          body: ""

      # The PR will still require manual approval, this just reduces it to a one-click process
      - name: Enable automerge
        if: steps.create_pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@60812ab1c2c6c6a8932b4d6e059becafaf386256 # v2.3.0
        with:
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          merge-method: squash
