---
name: "Update and test ehrql tutorial"

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build and publish image
    branches:
      - main
    types:
      - completed

jobs:
  create_tutorial_version_pr:
    if: ${{ (github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: opensafely-core/setup-action@v1
        with:
          install-just: true
          python-version: "3.11"

      - name: Install opensafely
        run: pip install opensafely

      - name: Update ehrql image version in tutorial project.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: just docs-update-tutorial-ehrql-version

      - name: Check dataset definitions outputs can be built with OpenSAFELY CLI project.yaml
        run: just docs-build-dataset-definitions-outputs-docker-project

      - name: Create a Pull Request if there are any changes
        id: create_pr
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          add-paths: |
            docs/ehrql-tutorial-examples/project.yaml
            docs/ehrql-tutorial-examples/outputs/*
          branch: bot/update-tutorial-version
          base: main
          author: "opensafely-github-bot <opensafely-github-bot@users.noreply.github.com>"
          committer: "opensafely-github-bot <opensafely-github-bot@users.noreply.github.com>"
          commit-message: "chore: Update ehrql version in tutorial project.yaml"
          title: "Update ehrql version in tutorial project.yaml"
          body: |
            To get tests to run on this PR there's an odd workflow:
             - Approve it
             - Close it
             - Re-open it
             - Re-enable automerge

            You can read more on why this is needed in the `create-pull-request` [docs][1].

            [1]: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

      # The PR will still require manual approval, this just reduces it to a one-click process
      - name: Enable automerge
        if: steps.create_pr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --squash ${{ steps.create_pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
